### PR TITLE
Update x/mod dependency for the new golang version format

### PR DESCRIPTION
**Pull request by Arlet2**
Update dependency for parsing go.mod file. Now it can parse go.mod with the new golang version format 1.23.3 instead of the old format 1.21

### CODE REVIEW

**Comment by qequ** [comment]
Hi, @Arlet2 thanks for the PR, can you check the pipeline that breaks? it seems to be related to x

**Comment by parvez3019** [comment]
Hi @Arlet2 also can you please remove `vendor` package from the PR, and put that in `.gitignore`

**Comment by Arlet2** [comment]
Hi, @parvez3019! I pushed your suggestions to PR

**Review by parvez3019 — APPROVED** [review]
LGTM, thanks

**Review by qequ — APPROVED** [review]

**Comment by qequ** [comment]
LGTM

**Pull request merged**
