### PR TITLE
Added Github Continuous Integration/Continuous Deployment pipeline and go-Linter

### PR DESCRIPTION
**Pull request by tarunsamanta2k20**
Added support for Github Continuous Integration/Continuous Deployment pipeline and go-Linter.

#24 
@tarunsamanta2k20

### CODE REVIEW

**Comment by tarunsamanta2k20** [comment]
@qequ Run workflows once. Let's see.

**Comment by parvez3019** [comment]
LGTM, Thanks for adding this @tarunsamanta2k20

**Comment by tarunsamanta2k20** [comment]
@parvez3019 I have a question. How did you trigger(run) this pipeline after my pushed. I am facing similar issue in other repo. Please let me know.

**Comment by parvez3019** [comment]
I triggered then via actions, it was giving me options to run the added workflows after your changes!

**Pull request merged**
