### PR TITLE
Feature - hide refs in custom Data types

### PR DESCRIPTION
**Pull request by qequ**
Added functionality to get strings from cli and delete them from custom types refs.

e.g. if we have a custom type named `github.com.username.project.name.model.MyStruct` and we pass `github.com.username.project.name.` to CLI's `--hide-refs` option, the Components' object and $refs of that object will be of the form `model.MyStruct`

Added tests.

### CODE REVIEW

**Comment by parvez3019** [comment]
@qequ Can you also add this to README?

**Comment by parvez3019** [comment]
@qequ I already added a CLI flag which is `schema-without-pkg` which is passed as true, generating schemas without pkg name. 
Can you check if that can be used for this use case instead of this?

**Comment by qequ** [comment]
This is exactly the feature I was looking for! I didn't notice it at first. Thanks @parvez3019

**Comment by parvez3019** [comment]
@qequ I'll add this to readme.

**Pull request closed without merging**
